@hostname = localhost
@port = 4001
@host = {{hostname}}:{{port}}/api/v1
@contentType = application/json

### create categories
POST http://{{host}}/categories
Content-Type: {{contentType}}

{
  "name": "Computers",
  "description": "Check each product page for other buying options."
}


### list categories
GET http://{{host}}/categories
Content-Type: {{contentType}}

### get category
GET http://{{host}}/categories/0f9fdf50-7240-4610-800e-abfd4dfc20f1
Content-Type: {{contentType}}

### update category
PUT http://{{host}}/categories/0f9fdf50-7240-4610-800e-abfd4dfc20f9
Content-Type: {{contentType}}

{
  "name": "some-category",
  "description": "some description"
}

### delet category
DELETE  http://{{host}}/categories/7831801f-bc4a-48eb-9584-0e384b7f835e
Content-Type: {{contentType}}

### create product
POST http://{{host}}/products
Content-Type: {{contentType}}

{
  "categoryId": "67fb7854-2ab1-4427-b428-90b69f70b78c",
  "name": "Laptop Samsung Galaxy PRO 3",
  "description": "Save time with card offload speeds of up to 200MB/s powered by SanDisk QuickFlow Technology (Up to 200MB/s read speeds.",
  "price": 652.42,
  "image": "https://media.licdn.com/dms/image/D4E22AQGlNjDfIs2lew/feedshare-shrink_800/0/1718865016429?e=1721865600&v=beta&t=Ota1r3eiXzBupVvqC1CcGAb6GadsIVAvdd7_pr2ZSAI"
}

### list products
GET http://{{host}}/products
Content-Type: {{contentType}}


### update product
PUT http://{{host}}/products/df5115f7-b4fd-4247-a21a-251ebef3e7c9
Content-Type: {{contentType}}

{
  "categoryId": "0f9fdf50-7240-4610-800e-abfd4dfc20f9",
  "name": "Laptop Samsung Galaxy PRO 6",
  "description": "Save time with card offload speeds of up to 200MB/s powered by SanDisk QuickFlow Technology (Up to 200MB/s read speeds.",
  "price": 652.42
}

### get product
GET  http://{{host}}/products/laptop-samsung-galaxy-pro-6-196e983c7
Content-Type: {{contentType}}

### delete product
DELETE http://{{host}}/products/5d775347-2d81-469a-9cfb-5fdf29d969ae
Content-Type: {{contentType}}


